import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col  w-screen h-screen bg-primary items-center ">
        <img
          src="/assets/logo.png"
          className="w-[102px] h-[54px] object-contain mx-auto mt-10"
          alt=""
        />
        <span className="flex justify-center items-center bg-green-grad bg-center mt-[20px] h-[300px] w-[620px] min-w-max bg-no-repeat">
          <h1 className="text-white text-[64px] font-bold w-[700px] text-center leading-[64px]">
            Liquidate your crypto with us
          </h1>
        </span>
        <p className="text-[#FCFCFC] opacity-60 text-[32px] w-[570px] text-center leading-9 mt-[20px]">
          Now borrow and lend crypto across the Ethereum Network
        </p>
        <button
          onClick={() => {
            location.href = "/app";
          }}
          className="bg-white py-[17px] px-[48px] rounded-[108px] font-bold text-[24px] mt-[32px]"
        >
          Go to the App
        </button>
        <img src="/assets/hero-img.svg" className="m-[44px]" alt="" />
      </div>
    </>
  );
}
